name: Community Check

on:
  workflow_call:
    inputs:
      username:
        description: The username to check the association of
        type: string
        required: true

    outputs:
      core_contributor:
        description: Whether or not the user is a core contributor
        value: ${{ jobs.check.outputs.core_contributor }}

      maintainer:
        description: Whether or not the user is a maintainer
        value: ${{ jobs.check.outputs.maintainer }}

      partner:
        description: Whether or not the user is a partner
        value: ${{ jobs.check.outputs.partner }}

## NOTE: !!!
## When changing these workflows, ensure that the following is updated:
##   - Documentation: docs/continuous-integration.md
##   - Documentation: docs/makefile-cheat-sheet.md
##   - Makefile: ./GNUmakefile

jobs:
  check:
    name: Check Lists
    runs-on: ubuntu-latest

    env:
      USER_LOGIN: ${{ inputs.username }}

    outputs:
      core_contributor: ${{ steps.core_contributor.outputs.in_list }}
      maintainer: ${{ steps.maintainer.outputs.in_list }}
      partner: ${{ steps.partner.outputs.in_list }}

    steps:
      - name: Core Contributor Check
        id: core_contributor
        run: |
          echo "in_list=$(echo ${{ secrets.CORE_CONTRIBUTORS }} | base64 --decode | jq --arg u $USER_LOGIN '. | contains([$u])')" >> "$GITHUB_OUTPUT"

      - name: Maintainer Check
        id: maintainer
        run: |
          echo "in_list=$(echo ${{ secrets.MAINTAINERS }} | base64 --decode | jq --arg u $USER_LOGIN '. | contains([$u])')" >> "$GITHUB_OUTPUT"

      - name: Partner Check
        id: partner
        run: |
          echo "in_list=$(echo ${{ secrets.PARTNERS }} | base64 --decode | jq --arg u $USER_LOGIN '. | contains([$u])')" >> "$GITHUB_OUTPUT"
